spring:
  datasource:
    # DataSource
    url: jdbc:mysql://localhost:8889/java?serverTimezone=Asia/Taipei
    username: root
    password: root
  jpa:
    # SessionFactory
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  messages:
    # i18n
    basename: error.Messages
    encoding: UTF-8
    fallback-to-system-locale: false

# tomcat server
server:
  port: 8081
  servlet:
    context-path: /boot    

#custom
password:
  length: 12
